id: 8db1c75db59146808226a284c96445c3
initial_creation_type: ocr
source_metadata:
  volumes:
    25e3f598a1574521ad1ae32bd5852978:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: གྲུབ་ཐོབ་ལྔ་བཅུའི་རྟོགས་པ་བརྗོད་པ་ཐིག་ལེ་འོད་ཀྱི་ཕྲེང་བ།
      total_pages: 1953
      volume_number: 27
